### ISSUE TITLE
Add application usage instructions to blog page

### ISSUE THREAD

**Issue by lingocoder** [akud/modular-java-example#1]
I am [*developing a plugin*](https://bit.ly/mrJar). The other day, while looking for code to test my plugin with, I came across your [*Building Modular Java Applications with Gradle*](http://bit.ly/akudBlog) blog post. It really is an amazing effort you've achieved there @akud! I learned a ton of stuff from that page. Sincere thanks for sharing!

All the steps needed to ***build*** your application were crystal clear in your blog. However, I struggled on working out how to actually ***use*** your application you detail there. Usage instructions would be a valuable improvement to that otherwise awesome blog page.

Incidentally, I'm interested in getting feedback from you @akud  on [*the improvements I made to the Gradle build*](http://bit.ly/mrJarZard) using my plugin as a replacement for the one you used originally. Please try to build and run my demo project in your own environment? Please let me know what works and what doesn't? 

From your point of view as the original author of the modular application,  have I overlooked anything either in my demo project's build script or in that demo repo's *`README`* that details your application's usage instructions? Thanks in advance for your response :+1:

**Comment by lingocoder** [comment]
***CC***: @zyxist

**Comment by akud** [comment]
Hi @lingocoder, thanks for the kind words! I'll have some time tomorrow (Thursday) to update the readme here and take a look at your plugin.

**Comment by lingocoder** [comment]
Hi @akud Cool! Thanks.

I put up [*a Spring Boot port of that demo*](http://bit.ly/mrSpringBoot). That new demo's interface is not as rich nor as interactive as your original Dropwizard one. But probably nobody will ever use mine anyway. So nobody will ever notice any difference :)

**Comment by akud** [comment]
Hi @lingocoder ,

Ok, I'm lame. I'm responding late, I apologize.

I took a look at your repos. Here are some thoughts:

* It's typical for gradle projects to have the gradle wrapper committed to the repo. That way every contributor uses the same gradle version. You can do this by running `gradle wrapper` and then committing the `gradle` directories and the `gradlew` executables

* I tried running the spring boot project and it didn't succeed:
```
alex@alex-lenovo:~/workspace/jpms.springboot.jersey$ ./gradlew checkAll

FAILURE: Build failed with an exception.

* What went wrong:
Task 'checkAll' not found in root project 'jpms.springboot.jersey'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
alex@alex-lenovo:~/workspace/jpms.springboot.jersey$ ./gradlew assembleAll

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAll' not found in root project 'jpms.springboot.jersey'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```
I gather that that might be because there is no top-level `build.gradle` or `settings.gradle`, which is very strange to me. Each gradle project has one `settings.gradle` at the top level; that's what defines the sub-projects.

* I also couldn't run `gradle wrapper` for the original project:

```
alex@alex-lenovo:~/workspace/mrJar.wizard$ gradle wrapper

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'mister.jar'.
> Could not set unknown property 'archiveBaseName' for task ':jar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
```

I don't know what that's about.

I'll go into some more general questions from reading the first `mr.Jar` project.

First, I noticed that you configured all the subprojects within the top-level build.gradle. I typically prefer that the top-level build.gradle contain common configuration and then each of the subprojects  configures itself within its own build.gradle file. That prevents the top-level build.gradle from growing out of control. This project is pretty simple since it only has three modules, but another project I work on has more than 20. With that many subprojects being configured in one place, the top-level build.gradle would be unwieldy.

Second, what would you say are the main advantages of your plugin over the chainsaw one? I notice that you don't have the `javaModule.hacks` section with packages being opened to unit tests, which is nice to not have to do but certainly not a deal breaker for the chainsaw plugin. I notice that you still also have to have the various _exclude & include_ portions in dependency management, e.g.:

```
        implementation(group: 'io.dropwizard', name: 'dropwizard-hibernate', version: '1.2.9') {
          exclude group: 'com.google.code.findbugs', module: 'jsr305'
          exclude group: 'org.jboss.spec.javax.transaction', module: 'jboss-transaction-api_1.2_spec'
        }
```
In my view, this is representative of the major challenge in building modular java applications from scratch. You have to make your dependency tree conform to the rules in the jpms system, whereas previously there were no rules on the dependency tree. Getting that to work is a big hurdle; the real challenge is figuring out which dependencies to exclude, which to modify, which to use different versions for, etc. I don't really see how a plugin could help with that part, but if it could, that would represent an order-of-magnitude improvement in building modular applications from scratch.

Hope this feedback helps!

**Comment by lingocoder** [comment]
> • It's typical for gradle projects to have the gradle wrapper committed to the repo....

Yeah. I typically do. I think what happened was, I must've copied a *`.gitignore`* from another project that ignores jar files and whatnot by default. I'll fix that. Thanks for the heads-up.


> • I tried running the spring boot project and it didn't succeed:
      `alex@alex-lenovo:~/workspace/jpms.springboot.jersey$ ./gradlew checkAll`
       ...


My mistake again. You need to *`cd`* into the *`authn`* folder first. Then run those tasks I listed. I guess I need to practice what I preach and get my own *`README`* in shape first, huh? :)

I will reply to your other replies later, @akud. But I just wanted to quickly shoot these to you right now.

**Comment by akud** [comment]
> You need to cd into the authn folder first

I get a different error when I run `gradle checkAll` from the `authn` directory:

```
~/workspace/jpms.springboot.jersey/authn$ gradle checkAll
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':mr.jar.authn.client'.
> Failed to notify project evaluation listener.
   > Could not set unknown property 'archiveBaseName' for task ':mr.jar.authn.client:jar' of type org.gradle.api.tasks.bundling.Jar.
   > Could not set unknown property 'archiveBaseName' for task ':mr.jar.authn.client:bootJar' of type org.springframework.boot.gradle.tasks.bundling.BootJar.
   > Could not find method getArchiveFile() for arguments [] on task ':mr.jar.authn.client:jar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
```

**Comment by lingocoder** [comment]
Hey thanks for the heads-up @akud :+1:

I've created [*Issue \#1*](https://github.com/lingocoder/jpms.springboot.jersey/issues/1) & [*Issue \#2*](https://github.com/lingocoder/jpms.springboot.jersey/issues/2) on that repo for those problems.

If you get time to jot down, please, what version of Gradle and whatnot you were using on [*\#2*](https://github.com/lingocoder/jpms.springboot.jersey/issues/2), that would be awesome! TIA :+1:
